# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- test

pool:
  vmImage: 'ubuntu-20.04'
variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm build 
    npm link
  displayName: 'npm install and build'

- script: |
    npm run ACE-AUTH
  displayName: 'testing Build scripts'
  continueOnError: true
  timeoutInMinutes: 240 # how long to run the job before automatically cancelling
#  cancelTimeoutInMinutes: 0 # how much time to give 'run always even if cancelled tasks' before stopping them  

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**.xml'
    testRunTitle: 'E2E Test'
